[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/utils.lua"]'''
pattern = '''-- TARGET: card destroyed'''
position = "after"
payload = '''
if next(SMODS.find_card('j_drx1_stamp')) then
    if destroyed == true then
        SMODS.calculate_context({drx1_cardtryingtobedestroyed = true, other_card = card})
    end
    destroyed = nil
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
match_indent = true
position = 'after'
pattern = '''
if G.GAME.blind.name == 'The Serpent' and
    not G.GAME.blind.disabled and
    (G.GAME.current_round.hands_played > 0 or
    G.GAME.current_round.discards_used > 0) then
        hand_space = math.min(#G.deck.cards, 3)
end
'''
payload = '''
local flags = SMODS.calculate_context({hand_space = hand_space})
hand_space = flags.hand_space or hand_space
'''

[[patches]]
[patches.pattern]
target = 'game.lua'
match_indent = true
position = 'after'
pattern = '''
win_ante = 8,
'''
payload = '''
grogoroth = 1,
'''

[[patches]]
[patches.pattern]
target = 'card.lua'
match_indent = true
position = 'at'
pattern = '''
self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)/100))
'''
payload = '''
self.cost = math.max(1, math.floor((self.base_cost + self.extra_cost + 0.5)*(100-G.GAME.discount_percent)*G.GAME.grogoroth/100))
'''